language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35

    - python: 3.6
      env: TOXENV=py36,mypy,flake8

install:
  - python -m pip install -U pip
  - python -m pip install -U tox

script: tox

# After you create the Github repo and add it to Travis, predefine
# TWINE_USERNAME and TWINE_PASSWORD environment variables in your travis-ci
# project settings, so that twine will access them without place the private
# account informations in this travis configuration file.
after_success:
  - |
    # Only deploy on python 3.6 and tag version
    if [ -n "${TRAVIS_TAG}" ] && [ "${TRAVIS_PYTHON_VERSION}" == "3.6" ] ; then
      python -m pip install twine
      python setup.py sdist --formats=zip
      twine upload dist/*
    fi
