language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34

    - python: 3.5
      env: TOXENV=py35

    - python: 3.6
      env: TOXENV=py36,mypy,flake8

install:
  - python -m pip install -U pip
  - python -m pip install -U tox
  - python -m pip install -U click
  - sudo python ./ci/install-qt-packages.py ${TRAVIS_PYTHON_VERSION}

script:
  - tox -e ${TOXENV}

deploy:
  provider: pypi
  distributions: sdist
  user: starofrainnight
  password:
    secure: cFc47RSPO8dzf5/tiDkZwRo+4wFln9fOz4eZWwB1j3NXhtvjJ4NJDRqqMSb1KnUTO0t3OF1ANt9+E+tgSRisfrmNEMEPTlRzazKZpdcArC1ZOow44mmEKHXeoLGyheZjAXyxbB9/LeYRDnYSA7vopO1pjCJVmsdOcO5AuRjpZfBgSGaOOelJpTge9Lyy/UHiS5S4bom9Hpz22lbgohdcVPDqD1w6VRBBZpv7EVAjRB5Q8KmcQDyKOD1RV9H4gRL9UJV9GJSsu0mfScGmXSMlHOMISApEXRr3zLbGJyWB3Huockem/n5QUC7Bua9ytdxHqykyXXHKPdzXqbMeMGTTciGEYXiN1Aclx2QA3fcU4+VA7imyeDDKa1AMSnho/OXF0jQSWTJHffWHl4CAeKZPnfx8fBlWdmWE19sUjbEa6eKwWjcEKAz4wwnN2/B4blzBcPQUv0XyXeg8ArvTdH9/XbWf+hjpIZa8tPn0b6wzqJY5mLY6DBVSUqLJHqKHbCbjfSHQjXV6ZK4Aq+2AVW3imuRgMjp85/bQRcy74GEG6zUMmc6icfp64DmftFNAbwJ102okUgaoWkjM8sjuZKyIlwcjzMRqq0aJWRXz82AXhIcV9/s4tb8jiblPPc5pGM6jHFdObUWKD9ETC3tGq9NWIv/5iJwjvq3ABiZhJLCjli4=
  on:
    tags: true
    repo: starofrainnight/rabird.qt
    python: 3.6
